-- New Cloudflare D1 database. No existing customer data is embedded.
CREATE TABLE IF NOT EXISTS submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL,
  interest TEXT NOT NULL, message TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
  body TEXT NOT NULL, approved INTEGER NOT NULL DEFAULT 0 CHECK(approved IN (0,1)),
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS reviews_public ON reviews(approved,id);
CREATE TABLE IF NOT EXISTS site_content (
  section TEXT PRIMARY KEY, draft TEXT NOT NULL, published TEXT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS editor_sessions (
  token TEXT PRIMARY KEY, csrf TEXT NOT NULL, expires INTEGER NOT NULL,
  credential TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_expiry ON editor_sessions(expires);
CREATE TABLE IF NOT EXISTS rate_limits (
  key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, expires INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS rate_expiry ON rate_limits(expires);
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('hero','{"hero_line1": "Your ambition.", "hero_line2": "A new horizon.", "hero_line3": "Expertly guided.", "hero_description": "Extraordinary journeys begin with thoughtful advice. Personal immigration guidance for the life you want to build.", "hero_button": "Begin your free assessment", "hero_caption": "London, United Kingdom", "hero_image": "", "hero_alt": "The Palace of Westminster and River Thames in London"}','{"hero_line1": "Your ambition.", "hero_line2": "A new horizon.", "hero_line3": "Expertly guided.", "hero_description": "Extraordinary journeys begin with thoughtful advice. Personal immigration guidance for the life you want to build.", "hero_button": "Begin your free assessment", "hero_caption": "London, United Kingdom", "hero_image": "", "hero_alt": "The Palace of Westminster and River Thames in London"}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('destinations','{"destinations_title": "Somewhere new.", "destinations_emphasis": "Something extraordinary.", "destinations_intro": "Four remarkable destinations. A world of different possibilities. Find the place that feels like your future."}','{"destinations_title": "Somewhere new.", "destinations_emphasis": "Something extraordinary.", "destinations_intro": "Four remarkable destinations. A world of different possibilities. Find the place that feels like your future."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('services','{"services_title": "Your plans are personal.", "services_emphasis": "Our guidance is, too.", "services_intro": "From a first opportunity abroad to a lasting home, our expertise brings clarity to your next move."}','{"services_title": "Your plans are personal.", "services_emphasis": "Our guidance is, too.", "services_intro": "From a first opportunity abroad to a lasting home, our expertise brings clarity to your next move."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('office','{"office_title": "Based in Colombo. Connected to the world.", "office_subtitle": "In-person and online consultations", "office_hours": "Let’s find a time that works.", "office_note": "Request your consultation through the assessment form."}','{"office_title": "Based in Colombo. Connected to the world.", "office_subtitle": "In-person and online consultations", "office_hours": "Let’s find a time that works.", "office_note": "Request your consultation through the assessment form."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('service_1','{"service_0_title": "Skilled migration", "service_0_text": "A considered pathway for your experience, qualifications, and ambitions."}','{"service_0_title": "Skilled migration", "service_0_text": "A considered pathway for your experience, qualifications, and ambitions."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('service_2','{"service_1_title": "Work & opportunity", "service_1_text": "Personal guidance for your next professional chapter overseas."}','{"service_1_title": "Work & opportunity", "service_1_text": "Personal guidance for your next professional chapter overseas."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('service_3','{"service_2_title": "Business & investment", "service_2_text": "Thoughtful support for founders and internationally minded entrepreneurs."}','{"service_2_title": "Business & investment", "service_2_text": "Thoughtful support for founders and internationally minded entrepreneurs."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('service_4','{"service_3_title": "Study abroad", "service_3_text": "From your academic aspirations to a well-prepared student application."}','{"service_3_title": "Study abroad", "service_3_text": "From your academic aspirations to a well-prepared student application."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('service_5','{"service_4_title": "Travel & visit", "service_4_text": "Careful preparation for family visits, business travel, and new discoveries."}','{"service_4_title": "Travel & visit", "service_4_text": "Careful preparation for family visits, business travel, and new discoveries."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('service_6','{"service_5_title": "Document services", "service_5_text": "Coordinated attestation and translation, with attention to every detail."}','{"service_5_title": "Document services", "service_5_text": "Coordinated attestation and translation, with attention to every detail."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('destination_1','{"destination_0_note": "A new perspective on possibility.", "destination_0_program": "Skilled migration · Work · Study", "destination_0_image": ""}','{"destination_0_note": "A new perspective on possibility.", "destination_0_program": "Skilled migration · Work · Study", "destination_0_image": ""}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('destination_2','{"destination_1_note": "More room for your next chapter.", "destination_1_program": "Permanent residence · Work · Study", "destination_1_image": ""}','{"destination_1_note": "More room for your next chapter.", "destination_1_program": "Permanent residence · Work · Study", "destination_1_image": ""}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('destination_3','{"destination_2_note": "Global ambition. A place to belong.", "destination_2_program": "Business · Skilled work · Study", "destination_2_image": ""}','{"destination_2_note": "Global ambition. A place to belong.", "destination_2_program": "Business · Skilled work · Study", "destination_2_image": ""}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('destination_4','{"destination_3_note": "Discover a different way of living.", "destination_3_program": "Work · Residence · Mobility", "destination_3_image": ""}','{"destination_3_note": "Discover a different way of living.", "destination_3_program": "Work · Residence · Mobility", "destination_3_image": ""}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('about','{"about_title": "The backbone of every", "about_emphasis": "migrant’s success story.", "vision": "To be the backbone of every migrant’s success story and to offer unparalleled service whilst building dependable relationships with our clients and maintaining confidentiality throughout the process to promote success.", "mission": "At The World Migration, our team of licensed and qualified consultants work closely with clients to bring about the best solutions to all their immigration objectives whilst maintaining confidentiality and other high professional standards. We build strong networks in source countries and our in-depth knowledge of complex and diverse immigration laws that are constantly being updated help achieve optimum results. We invest our energy, experience and knowledge to help create brand new opportunities in the practice of immigration."}','{"about_title": "The backbone of every", "about_emphasis": "migrant’s success story.", "vision": "To be the backbone of every migrant’s success story and to offer unparalleled service whilst building dependable relationships with our clients and maintaining confidentiality throughout the process to promote success.", "mission": "At The World Migration, our team of licensed and qualified consultants work closely with clients to bring about the best solutions to all their immigration objectives whilst maintaining confidentiality and other high professional standards. We build strong networks in source countries and our in-depth knowledge of complex and diverse immigration laws that are constantly being updated help achieve optimum results. We invest our energy, experience and knowledge to help create brand new opportunities in the practice of immigration."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('welcome','{"welcome_0": "The World Migration is a renowned immigration consultancy with over a decade of expertise in this industry. Our client centric approach and dedicated service will ensure that our clients qualify and get through this process at the first attempt. With a global presence and fail safe operation strategy, we will help your dreams materialize.", "welcome_1": "The entire process of applying for a visa can not only be lengthy and complex but also stressful and expensive. Team up with us and we will simplify the whole process because we genuinely care and that is all it takes to make the difference. We are really excited to work with you!"}','{"welcome_0": "The World Migration is a renowned immigration consultancy with over a decade of expertise in this industry. Our client centric approach and dedicated service will ensure that our clients qualify and get through this process at the first attempt. With a global presence and fail safe operation strategy, we will help your dreams materialize.", "welcome_1": "The entire process of applying for a visa can not only be lengthy and complex but also stressful and expensive. Team up with us and we will simplify the whole process because we genuinely care and that is all it takes to make the difference. We are really excited to work with you!"}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('about_detail_1','{"about_detail_0": "We offer a variety of services including but not limited to, migration consulting services for skilled migrants, procuring work visas, investor visas, entrepreneur visas, study permits, visit visas and document attestation and translations for all countries across the globe. At present we specialize in procuring visas for Australia, Canada, Denmark and Entrepreneur visas for the United Kingdom."}','{"about_detail_0": "We offer a variety of services including but not limited to, migration consulting services for skilled migrants, procuring work visas, investor visas, entrepreneur visas, study permits, visit visas and document attestation and translations for all countries across the globe. At present we specialize in procuring visas for Australia, Canada, Denmark and Entrepreneur visas for the United Kingdom."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('about_detail_2','{"about_detail_1": "The World Migration is the brain child of a team of experts with extensive and in-house experience in the UK and Canadian Immigration Departments. This consultancy has been set up post the retirement of our team members with the vision of helping people to get their visa application processed smoothly. You can be rest assured that you will fully qualify for the chosen visa of your preference with our impartial advice, offered free of charge even before you become a paying client."}','{"about_detail_1": "The World Migration is the brain child of a team of experts with extensive and in-house experience in the UK and Canadian Immigration Departments. This consultancy has been set up post the retirement of our team members with the vision of helping people to get their visa application processed smoothly. You can be rest assured that you will fully qualify for the chosen visa of your preference with our impartial advice, offered free of charge even before you become a paying client."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('about_detail_3','{"about_detail_2": "The World Migration is a trusted name in the migration consultancy field with a global presence and we are accredited by the Immigration Consultants of Canada Regulatory Council (ICCRC) and Migration Agents Registration Authority (MARA) in Australia. We truly believe that integrity and honesty should be a key part of the proceedings and the services provided here conform to the highest global standards."}','{"about_detail_2": "The World Migration is a trusted name in the migration consultancy field with a global presence and we are accredited by the Immigration Consultants of Canada Regulatory Council (ICCRC) and Migration Agents Registration Authority (MARA) in Australia. We truly believe that integrity and honesty should be a key part of the proceedings and the services provided here conform to the highest global standards."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('about_detail_4','{"about_detail_3": "Well, you may rightfully ask, why The World Migration over any other consultancy? We are very proud about the fact that we are extremely honest, reliable and provide service that is 100% value for money. Further, scores of people have benefitted from our “no obligation free visa assessment” that has guided them throughout the complex process with our step by step assistance. Furthermore, we are very pleased to announce that most of our new clients are referral clients and our biggest marketing tool has been word of mouth referral by past clients. For a journey that will be truly special, join hands with The World Migration."}','{"about_detail_3": "Well, you may rightfully ask, why The World Migration over any other consultancy? We are very proud about the fact that we are extremely honest, reliable and provide service that is 100% value for money. Further, scores of people have benefitted from our “no obligation free visa assessment” that has guided them throughout the complex process with our step by step assistance. Furthermore, we are very pleased to announce that most of our new clients are referral clients and our biggest marketing tool has been word of mouth referral by past clients. For a journey that will be truly special, join hands with The World Migration."}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('contact','{"contact_title": "Great journeys begin", "contact_emphasis": "with a conversation.", "contact_intro": "Tell us a little about yourself and your ambitions. We’ll help you explore what comes next, with a complimentary initial assessment.", "contact_form_title": "Your complimentary assessment"}','{"contact_title": "Great journeys begin", "contact_emphasis": "with a conversation.", "contact_intro": "Tell us a little about yourself and your ambitions. We’ll help you explore what comes next, with a complimentary initial assessment.", "contact_form_title": "Your complimentary assessment"}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('social_links','{"social_facebook": "", "social_linkedin": "", "social_instagram": "", "social_youtube": "", "social_x": "", "social_whatsapp": ""}','{"social_facebook": "", "social_linkedin": "", "social_instagram": "", "social_youtube": "", "social_x": "", "social_whatsapp": ""}');
INSERT OR IGNORE INTO site_content(section,draft,published) VALUES('quick_links','{"quicklink_whatsapp_label": "Call On WhatsApp", "quicklink_whatsapp_url": "", "quicklink_virtual_office": "", "quicklink_privacy_url": "", "quicklink_terms_url": "", "quicklink_disclaimer_url": ""}','{"quicklink_whatsapp_label": "Call On WhatsApp", "quicklink_whatsapp_url": "", "quicklink_virtual_office": "", "quicklink_privacy_url": "", "quicklink_terms_url": "", "quicklink_disclaimer_url": ""}');
